### ISSUE TITLE
Unsupported operand when entering Gentry's House

### ISSUE THREAD

**Issue by connorff** [GDcheeriosYT/Gentrys-Quest-Python#53] opened 2023-01-10 19:53 UTC
When entering Gentry's House lvl0-19. Here's the stack trace:
```
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    game.start(args.character)
  File "/home/connor/apl/Gentrys-Quest-Python/game/Game.py", line 133, in start
    location.select_area(self.equipped_character, self.game_data.inventory, self.game_data.content)
  File "/home/connor/apl/Gentrys-Quest-Python/game/Location/Location.py", line 35, in select_area
    self.areas[choice].start(character, inventory, content)
  File "/home/connor/apl/Gentrys-Quest-Python/game/Location/BattleArea/BattleArea.py", line 202, in start
    artifacts = ItemList(content_type=Artifact, content=self.initialize_artifacts(character.difficulty, content.families))
  File "/home/connor/apl/Gentrys-Quest-Python/game/Location/BattleArea/BattleArea.py", line 172, in initialize_artifacts
    artifact = artifact(StarRating(star_rating))
  File "/home/connor/apl/Gentrys-Quest-Python/game/Content/Artifacts/GMoney.py", line 20, in __init__
    super().__init__(
  File "/home/connor/apl/Gentrys-Quest-Python/game/Entity/Artifact/Artifact.py", line 70, in __init__
    self.main_attribute.handle_value(self.star_rating.value)
  File "/home/connor/apl/Gentrys-Quest-Python/game/Entity/Stats/Buff.py", line 70, in handle_value
    calculation = ((self.experience.level * 1.75) + (star_rating * 1.25) + (star_rating * int(self.experience.level / star_rating)))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by GDcheeriosYT** [comment] 2023-01-12 05:23
Yes, this is a duplicate of #51. It's a battle area thing. I have an idea of how this is happening.

**Closed by GDcheeriosYT** 2023-01-12 05:23 UTC
